apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap-3-{{ .Values.global.appName }}
  namespace: {{ .Release.Namespace }}
data:
  incidents.topic.name: {{ .Values.global.kafka.topics.category.service.incidents.name }}
  incidentsModificationRequests.topic.name: {{ .Values.global.kafka.topics.category.service.incidentsModificationRequests.name }}
  incidentsEnrichment.topic.name: {{ .Values.global.kafka.topics.category.service.incidentsEnrichment.name }}
